name: build

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            yio

jobs:
  build:
    if: github.repository == 'yiochou/Resume'
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [macos-latest]
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install markdown
      run: pip3 install markdown
    - name: Make resume
      run: python3 resume.py
    - name: Archive resume.html and resume.pdf
      uses: actions/upload-artifact@v2
      with:
          path: |
              *.pdf
              *.html
